import { getItemSummaries, getItemDetail } from './api';
import { Item } from '../types/Item';

test('getItemSummaries', async () => {
  const expectData = [[10057, '롱기누스: 제타', '31887', 135, 4, 5, 50]];
  const { data } = await getItemSummaries();
  expect(data).toEqual(expectData);
});

test('getItemDetail', async () => {
  const expectData: Item = {
    id: 28292,
    description: '',
    name: '절 롱고미안트',
    icon: '31993',
    itemLevel: 475,
    rarity: 3,
    itemUICategory: {
      id: 5,
      name: '양손창',
      icon: '60104',
      majorOrder: 4,
      minorOrder: 1,
    },
    stackSize: 1,
    isUnique: false,
    isUntradable: false,
    isIndisposable: false,
    lot: false,
    midPrice: 2,
    lowPrice: 0,
    canBeHq: false,
    isDyeable: false,
    isCrestWorthy: false,
    cooldown: 0,
    repairClassJob: '대장장이',
    repairItem: '7등급 암흑물질',
    glamourItem: '환상의 프리즘',
    salvage: null,
    isCollectable: false,
    alwaysCollectable: false,
    aetherialReduce: 0,
    equipLevel: 80,
    equipRestriction: 1,
    classJobCategory: '창술사 용기사',
    grandCompany: '총사령부 없음',
    itemSeries: '',
    baseParamModifier: 2,
    useClassJob: '창술사',
    physDamage: 122,
    magDamage: 82,
    delay: 2800,
    blockRate: 0,
    block: 0,
    physDefense: 0,
    magDefense: 0,
    baseParam0: '0',
    baseParamValue0: 544,
    baseParam1: '2',
    baseParamValue1: 585,
    baseParam2: '15',
    baseParamValue2: 467,
    baseParam3: '18',
    baseParamValue3: 327,
    baseParam4: '-1',
    baseParamValue4: 0,
    baseParam5: '-1',
    baseParamValue5: 0,
    itemSpecialBonus: '',
    itemSpecialBonusParam: 0,
    specialBaseParam0: '-1',
    specialBaseParamValue0: 0,
    specialBaseParam1: '-1',
    specialBaseParamValue1: 0,
    specialBaseParam2: '-1',
    specialBaseParamValue2: 0,
    specialBaseParam3: '-1',
    specialBaseParamValue3: 0,
    specialBaseParam4: '-1',
    specialBaseParamValue4: 0,
    specialBaseParam5: '-1',
    specialBaseParamValue5: 0,
    materializeType: 0,
    materiaSlotCount: 3,
    isAdvancedMeldingPermitted: false,
    isPvP: false,
    isGlamourous: false,
  };

  const { data } = await getItemDetail(28292);
  expect(data).toStrictEqual(expectData);
});
