language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - yarn test --coverage --collectCoverageFrom='["src/**/*.{ts,tsx}","!src/**/stories/*","!src/serviceWorker.ts","!src/index.tsx"]'
  - yarn add codecov -g
  - codecov -f coverage/*.json
