import { ItemUICategory } from './ItemUICategory';
import { ItemRarity } from './ItemRairity';
import { BaseParam } from './BaseParam';

export type Item = {
  id: number;
  description: string;
  name: string;
  icon: string;
  itemLevel: number;
  rarity: ItemRarity;
  itemUICategory: ItemUICategory;
  stackSize: number;
  isUnique: boolean;
  isUntradable: boolean;
  isIndisposable: boolean;
  lot: boolean;
  midPrice: number;
  lowPrice: number;
  canBeHq: boolean;
  isDyeable: boolean;
  isCrestWorthy: boolean;
  cooldown: number;
  repairClassJob: string | null;
  repairItem: string | null;
  glamourItem: string | null;
  salvage: number | null;
  isCollectable: boolean;
  alwaysCollectable: boolean;
  aetherialReduce: number;
  equipLevel: number;
  equipRestriction: number;
  classJobCategory: string;
  grandCompany: string;
  itemSeries: string;
  baseParamModifier: number;
  useClassJob: string;
  physDamage: number;
  magDamage: number;
  delay: number;
  blockRate: number;
  block: number;
  physDefense: number;
  magDefense: number;
  baseParam0?: BaseParam;
  baseParam1?: BaseParam;
  baseParam2?: BaseParam;
  baseParam3?: BaseParam;
  baseParam4?: BaseParam;
  baseParam5?: BaseParam;
  itemSpecialBonus: string;
  itemSpecialBonusParam: number;
  specialBaseParam0?: BaseParam;
  specialBaseParam1?: BaseParam;
  specialBaseParam2?: BaseParam;
  specialBaseParam3?: BaseParam;
  specialBaseParam4?: BaseParam;
  specialBaseParam5?: BaseParam;
  materializeType: number;
  materiaSlotCount: number;
  isAdvancedMeldingPermitted: boolean;
  isPvP: boolean;
  isGlamourous: boolean;
};
