import { ItemUICategory } from './ItemUICategory';

export type Item = {
  id: number;
  description: string;
  name: string;
  icon: string;
  itemLevel: number;
  rarity: number;
  itemUICategory: ItemUICategory;
  stackSize: number;
  isUnique: boolean;
  isUntradable: boolean;
  isIndisposable: boolean;
  lot: boolean;
  midPrice: number;
  lowPrice: number;
  canBeHq: boolean;
  isDyeable: boolean;
  isCrestWorthy: boolean;
  cooldown: number;
  repairClassJob: string | null;
  repairItem: string | null;
  glamourItem: string | null;
  salvage: number | null;
  isCollectable: boolean;
  alwaysCollectable: boolean;
  aetherialReduce: number;
  equipLevel: number;
  equipRestriction: number;
  classJobCategory: string;
  grandCompany: string;
  itemSeries: string;
  baseParamModifier: number;
  useClassJob: string;
  physDamage: number;
  magDamage: number;
  delay: number;
  blockRate: number;
  block: number;
  physDefense: number;
  magDefense: number;
  baseParam0: string;
  baseParamValue0: number;
  baseParam1: string;
  baseParamValue1: number;
  baseParam2: string;
  baseParamValue2: number;
  baseParam3: string;
  baseParamValue3: number;
  baseParam4: string;
  baseParamValue4: number;
  baseParam5: string;
  baseParamValue5: number;
  itemSpecialBonus: string;
  itemSpecialBonusParam: number;
  specialBaseParam0: string;
  specialBaseParamValue0: number;
  specialBaseParam1: string;
  specialBaseParamValue1: number;
  specialBaseParam2: string;
  specialBaseParamValue2: number;
  specialBaseParam3: string;
  specialBaseParamValue3: number;
  specialBaseParam4: string;
  specialBaseParamValue4: number;
  specialBaseParam5: string;
  specialBaseParamValue5: number;
  materializeType: number;
  materiaSlotCount: number;
  isAdvancedMeldingPermitted: boolean;
  isPvP: boolean;
  isGramourous: boolean;
};
